export const DEFAULT_RICHTEXT_FILL = 'none';
export const DEFAULT_RICHTEXT_FILL_OPACITY = 1;
export const DEFAULT_RICHTEXT_STROKE = '#ed556a';
export const DEFAULT_RICHTEXT_STROKE_WIDTH = 2;
export const DEFAULT_RICHTEXT_STROKE_OPACITY = 1;
